name: Node CI

on:
  push:
    paths-ignore:
      - demo/**/*

jobs:

  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14', '16']
    name: "[v${{ matrix.node-version }}] check"

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm ci

    - name: Run lint & tests
      env:
        CI: 1
      run: |
        npm run lint
        npm t

    - name: Submit coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
